# Generated by Django 4.2.21 on 2025-06-06 21:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=0)),
                ('current_weight', models.PositiveIntegerField(default=0)),
                ('sio2_percent', models.FloatField(default=0)),
                ('fe_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_weight', models.PositiveIntegerField(default=0)),
                ('sio2_percent', models.FloatField(default=0)),
                ('fe_percent', models.FloatField(default=0)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Unloading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('in_poligon', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dump_trucks.truck')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dump_trucks.warehouse')),
            ],
        ),
    ]
