# Generated by Django 4.2.21 on 2025-06-07 08:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.polygon
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dump_trucks', '0002_alter_truck_current_weight_alter_truck_fe_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default=django.contrib.gis.geos.polygon.Polygon(((0, 0), (0, 0), (0, 0), (0, 0), (0, 0))), srid=4326),
        ),
    ]
