# Generated by Django 4.2.21 on 2025-06-07 08:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dump_trucks', '0003_alter_warehouse_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text="Введите полигон в формате WKT, например: 'POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))'", srid=4326),
        ),
    ]
